---

- name: "Instlacja narzedzi uzytkownika noda boaccess"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja narzedzi uzytkownika" 
      yum:
        name: 
          - nano
          - less
          - vim
          - mc
          - ftp
          - cifs-utils
          - gawk
          - perl
          - unzip
          - screen
          - tcsh
          - dash
          - curl 
        state: present
        update_cache: yes
    - name: "Instalacja zaleznosci soge do poprawnego dzialania submit node"
      yum:
        name:
          - jemalloc
        state: present
        update_cache: yes
    - name: "Instalacja podstawowych narzedzi sieiowych"
      yum:
        name:
          - net-tools
        state: present
        update_cache: yes
    - name: "Instalacja srodowiska ssh"
      yum:
        name:
          - openssh-server.x86_64
          - openssh-clients.x86_64
        state: present
        update_cache: yes
    - name: "Tworzenie linku rsh do ssh"
      file:
        src: /usr/bin/ssh
        dest: /usr/bin/rsh
        state: link
    - name: "Generacja kluczy SSH"
      shell: /usr/bin/ssh-keygen -A
    - name: "Tworzenie katalogu konfiguracji klienta SSH"
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
    - name: "Konfiguracja klienta SSH"
      shell: echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
